#!/bin/bash



/Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake --build cmake-build-debug --target http_request_parser -j 6

# echo " ==========[ PROGRAM OUTPUT ]========== "

$HOME/CLionProjects/http-request-parser/cmake-build-debug/http_request_parser


